set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on
set -g detach-on-destroy off  # switch to another session instead of detaching

set -s escape-time 0      # make <Esc> and <C-h/j/k/l> feel instant
set -g focus-events on    # better focus handling for nvim

unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Quick config reload
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded"

# Clear screen (since C-l is used by vim-tmux-navigator)
bind L send-keys '^L'

# Pane resizing with prefix + arrow keys
bind Up resize-pane -U 5
bind Down resize-pane -D 5
bind Left resize-pane -L 5
bind Right resize-pane -R 5

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# vi-mode and copy keybindings
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind-key & kill-window
bind-key x kill-pane

bind - split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Pop-up windows
bind C-y display-popup -d "#{pane_current_path}" -w 80% -h 80% -E "lazygit"
bind C-j display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\\$\" | fzf --reverse | xargs tmux switch-client -t"
bind C-n display-popup -E 'bash -i -c "read -p \"Session name: \" name; tmux new-session -d -s \$name && tmux switch-client -t \$name"'
bind C-t display-popup -d "#{pane_current_path}" -w 75% -h 75% -E "zsh"

set -g @tokyo-night-tmux_show_datetime 0
set -g @tokyo-night-tmux_show_path 1
set -g @tokyo-night-tmux_path_format relative
set -g @tokyo-night-tmux_window_id_style dsquare
set -g @tokyo-night-tmux_show_git 0

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm'
