################
### MONITORS ###
################

# Description of main monitor
$main_monitor = LG Electronics LG ULTRAGEAR 111NTEP0L396

# Monitors
monitor = desc:$main_monitor, highres highrr, 0x0, 1 # Main
monitor = , preferred, auto, auto # Multi monitors

