#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)

# Authentication agent (for password prompts)
exec-once = hyprpolkitagent

exec-once = hyprctl setcursor win11-Dark 24

# Notification daemon (uncomment your preferred choice)
# exec-once = mako
# exec-once = dunst

# Status bar (uncomment your preferred choice)
exec-once = waybar
# exec-once = eww daemon && eww open bar

# Audio effects service
exec-once = easyeffects --hide-window --gapplication-service

# Wallpaper (uncomment your preferred choice)
exec-once = hyprpaper
# exec-once = swaybg -i ~/.config/hypr/wallpaper.jpg

# Network manager applet
# exec-once = nm-applet --indicator

# Clipboard manager
exec-once = wl-paste --watch cliphist store

# Idle management
exec-once = hypridle

# Screen sharing support
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = gnome-keyring-daemon --start --components=secrets
