#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = gbswe
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = -0.75 # -1.0 - 1.0, 0 means no modification.
    accel_profile = flat
    force_no_accel = true

    # Keyboard repeat settings
    repeat_rate = 25  # Characters per second when holding a key
    repeat_delay = 400  # Milliseconds before repeat starts

    touchpad {
        natural_scroll = false
        disable_while_typing = true
        tap-to-click = true
        clickfinger_behavior = true
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
# gestures {
#     workspace_swipe = true
#     workspace_swipe_fingers = 3
# }

