# --- Look and Feel ---
include tokyonight_night.conf
# font_family FiraCode Nerd Font
font_size 14.0
cursor_shape block
cursor_blink_interval 0

# Padding
window_padding_width 0 6

# Window chrome
hide_window_decorations titlebar-only
macos_option_as_alt left

# Mouse and interaction
mouse_hide_wait -1
copy_on_select yes
confirm_os_window_close 0

# Disable tab keybinds (using tmux)
map cmd+t no_op
map cmd+w no_op
map cmd+shift+left_bracket no_op
map cmd+shift+right_bracket no_op


# BEGIN_KITTY_FONTS
font_family      family="Fira Code"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
